global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins-server:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-server:80']  # This remains the same as it's referring to the container name

